spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 10768
help:
  default-license-name: Adonis
  default-assignee-name: Lau
  default-expiry-date: 2200-02-20
